// This file is generated by assets/update.ts - DO NOT EDIT MANUALLY
// Run 'bun assets/update.ts' to regenerate this file

import { resolveBundledFilePath } from "@opentui/core"
import type { FiletypeParserOptions, InjectionMapping } from "@opentui/core"

interface FileImportModule {
  readonly default: string
}

const bundledAssetLoaders: Record<string, () => Promise<FileImportModule>> = {
  "json/highlights.scm": () => import("./json/highlights.scm" as string, { with: { type: "file" } }),
  "json/tree-sitter-json.wasm": () => import("./json/tree-sitter-json.wasm" as string, { with: { type: "file" } }),
  "toml/highlights.scm": () => import("./toml/highlights.scm" as string, { with: { type: "file" } }),
  "toml/tree-sitter-toml.wasm": () => import("./toml/tree-sitter-toml.wasm" as string, { with: { type: "file" } }),
  "kotlin/highlights.scm": () => import("./kotlin/highlights.scm" as string, { with: { type: "file" } }),
  "kotlin/tree-sitter-kotlin.wasm": () => import("./kotlin/tree-sitter-kotlin.wasm" as string, { with: { type: "file" } }),
  "python/highlights.scm": () => import("./python/highlights.scm" as string, { with: { type: "file" } }),
  "python/tree-sitter-python.wasm": () => import("./python/tree-sitter-python.wasm" as string, { with: { type: "file" } }),
  "rust/highlights.scm": () => import("./rust/highlights.scm" as string, { with: { type: "file" } }),
  "rust/tree-sitter-rust.wasm": () => import("./rust/tree-sitter-rust.wasm" as string, { with: { type: "file" } }),
  "go/highlights.scm": () => import("./go/highlights.scm" as string, { with: { type: "file" } }),
  "go/tree-sitter-go.wasm": () => import("./go/tree-sitter-go.wasm" as string, { with: { type: "file" } }),
  "bash/highlights.scm": () => import("./bash/highlights.scm" as string, { with: { type: "file" } }),
  "bash/tree-sitter-bash.wasm": () => import("./bash/tree-sitter-bash.wasm" as string, { with: { type: "file" } }),
  "html/highlights.scm": () => import("./html/highlights.scm" as string, { with: { type: "file" } }),
  "html/tree-sitter-html.wasm": () => import("./html/tree-sitter-html.wasm" as string, { with: { type: "file" } }),
  "css/highlights.scm": () => import("./css/highlights.scm" as string, { with: { type: "file" } }),
  "css/tree-sitter-css.wasm": () => import("./css/tree-sitter-css.wasm" as string, { with: { type: "file" } }),
  "java/highlights.scm": () => import("./java/highlights.scm" as string, { with: { type: "file" } }),
  "java/tree-sitter-java.wasm": () => import("./java/tree-sitter-java.wasm" as string, { with: { type: "file" } }),
  "c/highlights.scm": () => import("./c/highlights.scm" as string, { with: { type: "file" } }),
  "c/tree-sitter-c.wasm": () => import("./c/tree-sitter-c.wasm" as string, { with: { type: "file" } }),
  "cpp/highlights.scm": () => import("./cpp/highlights.scm" as string, { with: { type: "file" } }),
  "cpp/tree-sitter-cpp.wasm": () => import("./cpp/tree-sitter-cpp.wasm" as string, { with: { type: "file" } }),
  "ruby/highlights.scm": () => import("./ruby/highlights.scm" as string, { with: { type: "file" } }),
  "ruby/tree-sitter-ruby.wasm": () => import("./ruby/tree-sitter-ruby.wasm" as string, { with: { type: "file" } }),
  "php/highlights.scm": () => import("./php/highlights.scm" as string, { with: { type: "file" } }),
  "php/tree-sitter-php.wasm": () => import("./php/tree-sitter-php.wasm" as string, { with: { type: "file" } }),
}

interface DefaultParserDescriptor {
  readonly filetype: string
  readonly aliases?: readonly string[]
  readonly queries: {
    readonly highlights: readonly string[]
    readonly injections?: readonly string[]
  }
  readonly wasm: string
  readonly injectionMapping?: InjectionMapping
}

const defaultParserDescriptors: readonly DefaultParserDescriptor[] = [
  {
    "filetype": "json",
    "aliases": [
      "jsonc"
    ],
    "queries": {
      "highlights": [
        "json/highlights.scm"
      ]
    },
    "wasm": "json/tree-sitter-json.wasm"
  },
  {
    "filetype": "toml",
    "queries": {
      "highlights": [
        "toml/highlights.scm"
      ]
    },
    "wasm": "toml/tree-sitter-toml.wasm"
  },
  {
    "filetype": "kotlin",
    "aliases": [
      "kt",
      "kts"
    ],
    "queries": {
      "highlights": [
        "kotlin/highlights.scm"
      ]
    },
    "wasm": "kotlin/tree-sitter-kotlin.wasm"
  },
  {
    "filetype": "python",
    "queries": {
      "highlights": [
        "python/highlights.scm"
      ]
    },
    "wasm": "python/tree-sitter-python.wasm"
  },
  {
    "filetype": "rust",
    "queries": {
      "highlights": [
        "rust/highlights.scm"
      ]
    },
    "wasm": "rust/tree-sitter-rust.wasm"
  },
  {
    "filetype": "go",
    "queries": {
      "highlights": [
        "go/highlights.scm"
      ]
    },
    "wasm": "go/tree-sitter-go.wasm"
  },
  {
    "filetype": "bash",
    "queries": {
      "highlights": [
        "bash/highlights.scm"
      ]
    },
    "wasm": "bash/tree-sitter-bash.wasm"
  },
  {
    "filetype": "html",
    "queries": {
      "highlights": [
        "html/highlights.scm"
      ]
    },
    "wasm": "html/tree-sitter-html.wasm"
  },
  {
    "filetype": "css",
    "queries": {
      "highlights": [
        "css/highlights.scm"
      ]
    },
    "wasm": "css/tree-sitter-css.wasm"
  },
  {
    "filetype": "java",
    "queries": {
      "highlights": [
        "java/highlights.scm"
      ]
    },
    "wasm": "java/tree-sitter-java.wasm"
  },
  {
    "filetype": "c",
    "queries": {
      "highlights": [
        "c/highlights.scm"
      ]
    },
    "wasm": "c/tree-sitter-c.wasm"
  },
  {
    "filetype": "cpp",
    "queries": {
      "highlights": [
        "cpp/highlights.scm"
      ]
    },
    "wasm": "cpp/tree-sitter-cpp.wasm"
  },
  {
    "filetype": "ruby",
    "queries": {
      "highlights": [
        "ruby/highlights.scm"
      ]
    },
    "wasm": "ruby/tree-sitter-ruby.wasm"
  },
  {
    "filetype": "php",
    "queries": {
      "highlights": [
        "php/highlights.scm"
      ]
    },
    "wasm": "php/tree-sitter-php.wasm"
  }
]

export const defaultParserAssetPaths: readonly string[] = [
  ...new Set(
    defaultParserDescriptors.flatMap((parser) => [
      ...parser.queries.highlights,
      parser.wasm,
      ...(parser.queries.injections ?? []),
    ]),
  ),
]

let cachedParsers: Promise<FiletypeParserOptions[]> | undefined

export function getParsers(): Promise<FiletypeParserOptions[]> {
  cachedParsers ??= Promise.all(defaultParserDescriptors.map(resolveDefaultParser))
  return cachedParsers
}

async function resolveDefaultParser(parser: DefaultParserDescriptor): Promise<FiletypeParserOptions> {
  const queries: FiletypeParserOptions["queries"] = {
    highlights: await Promise.all(parser.queries.highlights.map(resolveParserAsset)),
  }
  if (parser.queries.injections) {
    queries.injections = await Promise.all(parser.queries.injections.map(resolveParserAsset))
  }

  return {
    filetype: parser.filetype,
    ...(parser.aliases ? { aliases: [...parser.aliases] } : {}),
    queries,
    wasm: await resolveParserAsset(parser.wasm),
    ...(parser.injectionMapping ? { injectionMapping: parser.injectionMapping } : {}),
  }
}

function resolveParserAsset(relativePath: string): Promise<string> {
  const loadBundledFile = bundledAssetLoaders[relativePath]
  if (!loadBundledFile) {
    throw new Error(`Unknown parser asset: ${JSON.stringify(relativePath)}`)
  }
  return resolveBundledFilePath(
    relativePath,
    loadBundledFile,
    new URL(`./${relativePath}`, import.meta.url),
    import.meta.url,
    { loadBundledFileFallback: true, useAssetRoot: false },
  )
}
