/**
 * Collects every tree-sitter grammar the TUI registers — opentui's bundled
 * defaults plus the repo's `src/tui/syntax` parsers (`getParsers()`) — and
 * writes them for the browser:
 *
 *   dist/tree-sitter/<filetype>.js   one script per grammar: the wasm (base64)
 *                                    and its highlights/injections queries,
 *                                    loaded on demand (shipped as `_vendor/tree-sitter/`)
 *   .generated/treesitter.ts         the registry the shim bundles: filetypes,
 *                                    aliases, injection mappings, opentui's
 *                                    extension/basename → filetype tables and
 *                                    the web-tree-sitter runtime wasm
 *
 * opentui's own tables are read out of its compiled chunk rather than copied,
 * so an opentui upgrade can't silently drift; the build fails loudly if the
 * shapes move.
 */
import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { createRequire } from "node:module";

const PKG = import.meta.dir;
const ROOT = resolve(PKG, "../..");
const require = createRequire(join(ROOT, "package.json"));
const CORE_DIR = dirname(require.resolve("@opentui/core/package.json"));

interface Grammar {
  filetype: string;
  aliases: string[];
  wasm: string;
  highlights: string[];
  injections: string[];
  injectionMapping?: { nodeTypes?: Record<string, string>; infoStringMap?: Record<string, string> };
}

/** Pulls a `var <name> = <literal>;` out of opentui's compiled core. */
function extractLiteral(name: string, open: string): string {
  for (const file of readdirSync(CORE_DIR).filter((f) => /^chunk-node-.*\.js$/.test(f))) {
    const src = readFileSync(join(CORE_DIR, file), "utf8");
    const start = src.indexOf(`var ${name} = ${open}`);
    if (start === -1) continue;
    const from = start + `var ${name} = `.length;
    const end = src.indexOf("\n]", from);
    const tail = src.slice(end, end + 4);
    if (end === -1 || !/^\n\]\)?;/.test(tail)) break;
    return src.slice(from, end + (tail.startsWith("\n])") ? 3 : 2));
  }
  throw new Error(`[treesitter] couldn't find \`var ${name}\` in @opentui/core — its internals moved; update treesitter-assets.ts`);
}

export async function buildTreeSitterAssets(dist: string): Promise<{ grammars: number; bytes: number }> {
  // 1. opentui's defaults (javascript, typescript, markdown(+inline), zig).
  const coreDefaults = new Function(`return ${extractLiteral("defaultParserDescriptors", "[")}`)() as any[];
  const grammars: Grammar[] = coreDefaults.map((d) => ({
    filetype: d.filetype,
    aliases: d.aliases ?? [],
    wasm: join(CORE_DIR, d.wasm),
    highlights: d.queries.highlights.map((q: string) => join(CORE_DIR, q)),
    injections: (d.queries.injections ?? []).map((q: string) => join(CORE_DIR, q)),
    ...(d.injectionMapping ? { injectionMapping: d.injectionMapping } : {}),
  }));
  // 2. The repo's vendored parsers, exactly as `registerSyntaxParsers` adds them.
  const { getParsers } = await import(join(ROOT, "src/tui/syntax/parsers.ts"));
  for (const p of await getParsers()) {
    grammars.push({
      filetype: p.filetype,
      aliases: p.aliases ?? [],
      wasm: p.wasm,
      highlights: p.queries.highlights,
      injections: p.queries.injections ?? [],
      ...(p.injectionMapping ? { injectionMapping: p.injectionMapping } : {}),
    });
  }

  const outDir = join(dist, "tree-sitter");
  rmSync(outDir, { recursive: true, force: true });
  mkdirSync(outDir, { recursive: true });
  let bytes = 0;
  for (const g of grammars) {
    const payload = {
      wasm: readFileSync(g.wasm).toString("base64"),
      highlights: g.highlights.map((f) => readFileSync(f, "utf8")).join("\n"),
      injections: g.injections.length ? g.injections.map((f) => readFileSync(f, "utf8")).join("\n") : null,
    };
    const js = `(window.__mxTreeSitter=window.__mxTreeSitter||{})[${JSON.stringify(g.filetype)}]=${JSON.stringify(payload)};\n`;
    writeFileSync(join(outDir, `${g.filetype}.js`), js);
    bytes += js.length;
  }

  // 3. The registry + opentui's filetype tables + the runtime wasm, bundled into the shim.
  const registry = grammars.map((g) => ({
    filetype: g.filetype,
    aliases: g.aliases,
    hasInjections: g.injections.length > 0,
    ...(g.injectionMapping ? { injectionMapping: g.injectionMapping } : {}),
  }));
  const extensionMap = extractLiteral("extensionToFiletype2", "new Map([");
  const basenameMap = extractLiteral("basenameToFiletype2", "new Map([");
  const runtime = readFileSync(require.resolve("web-tree-sitter/tree-sitter.wasm")).toString("base64");
  mkdirSync(join(PKG, ".generated"), { recursive: true });
  writeFileSync(
    join(PKG, ".generated/treesitter.ts"),
    `// Generated by .design-sync/pkg/treesitter-assets.ts — do not edit.\n` +
      `export const GRAMMARS: { filetype: string; aliases: string[]; hasInjections: boolean; injectionMapping?: { nodeTypes?: Record<string, string>; infoStringMap?: Record<string, string> } }[] = ${JSON.stringify(registry)};\n` +
      `export const EXTENSION_TO_FILETYPE: Map<string, string> = ${extensionMap};\n` +
      `export const BASENAME_TO_FILETYPE: Map<string, string> = ${basenameMap};\n` +
      `export const RUNTIME_WASM_BASE64 = ${JSON.stringify(runtime)};\n`,
  );
  return { grammars: grammars.length, bytes };
}
